/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElMessage: typeof import('element-plus/es')['ElMessage']
  const ElMessageBox: typeof import('element-plus/es')['ElMessageBox']
  const IconEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
  const IconEpHouse: typeof import('~icons/ep/house')['default']
  const IconEpMenu: typeof import('~icons/ep/menu')['default']
  const IconEpSetting: typeof import('~icons/ep/setting')['default']
  const IconEpWarningFilled: typeof import('~icons/ep/warning-filled')['default']
  const iconElement: typeof import('~icons/el/ement')['default']
}
